name: system-v

on:
  push:
    branches: 
        - master
        - gh-actions

  pull_request:
    branches: 
        - master

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
       toolchain: stable
       override: true
    - name: gen1
      run: make